### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by henryboisdequin** [vikrameast/guess-number#1]
Create a separate CSS file for easier readability

**Comment by sahilrawat001** [comment]
Which project 's  css file to create

**Comment by RK995** [comment]
What about project

**Comment by NehaK275** [comment]
hi @henryboisdequin can i do this?

**Comment by henryboisdequin** [comment]
I'm sure @vikrameast would be open to a PR

**Comment by vikrameast** [comment]
@NehaK275 Please feel free.

**Comment by NehaK275** [comment]
@vikrameast should i add some more things like background image or just create a separate css file
